name: Package

on:
  release:
    types: [created]

jobs:
  publishJar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-dagger-cache-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-dagger-cache-
      - name: Publish packages of common subprojects
        run: ./gradlew :dagger-common:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish minimal package of core
        run: ./gradlew :dagger-core:minimalPublish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
